config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :posts
      root to: "users#index"
    end

  get '/favorites', to: 'favorite_posts#index', as: 'favorites'
  resources :favorite_posts, only: [:create, :destroy]

  resources :posts do
    resources :likes
    resources :readings
    resources :calls
    resources :teams
    resources :rejections
    resources :comments
  end
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  def commentable_type=(class_name)
    super(class_name.constantize.base_class.to_s)
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :readings, dependent: :destroy
  has_many :calls, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_many :rejections, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  has_one_attached :photo
  has_rich_text :rich_body

  validates_presence_of :deadline, :title, :client
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/rejection.rb
class Rejection < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :favorited, source_type: 'Post', dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :readings, dependent: :destroy
  has_many :calls, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_many :rejections, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates_presence_of :first_name, :last_name

  def admin?
    type == 'AdminUser'
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :find_post
  before_action :find_call, only: [:destroy]

  def create
    if already_called?
      flash[:notice] = "Vous ne pouvez pas le faire plus d'une fois."
    else
      @post.calls.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def find_call
    @call = @post.calls.find(params[:id])
  end

  def destroy
    if !(already_called?)
      flash[:notice] = "Vous ne pouvez pas annuler l'action"
    else
      @call.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_called?
    Call.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
      LikeMailer.creation_like(@post).deliver_now
    end
    redirect_to post_path(@post)
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id: params[:post_id]).exists?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_types
    ['AdminUser']
  end

  def admin?
    admin_types.include?(current_user.type)
  end

  def cloudinary_download_url(key, options = {})
    # Construction directe de l'URL Cloudinary
    resource_type = options[:resource_type] || "image"
    format = options[:format]
    transformation = options[:transformation] || "fl_attachment"

    url = "https://res.cloudinary.com/#{ENV['CLOUDINARY_CLOUD_NAME']}/#{resource_type}/upload/#{transformation}"
    url += "/#{key}"
    url += ".#{format}" if format

    url
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/helpers/rejections_helper.rb
module RejectionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tapas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,700|Work+Sans:400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <%  if notice %>
      <div class="flash flash-success alert alert-dismissible fade show" role="alert">
        <span><strong>Yay!</strong> 🎉 <%= notice %> </span>
        <a data-dismiss="alert" aria-label="Close">
          <i class="fas fa-times"> </i>
        </a>
      </div>
    <%  elsif alert %>
      <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
        <span><strong>Oops!</strong> 😱 <%= alert %> </span>
        <a data-dismiss="alert" aria-label="Close">
         <span><i class="fas fa-times"> </i></span>
        </a>
      </div>
    <% end %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_admin_add_ao.html.erb
<li class="nav-item">
  <%= link_to "AJOUTER UN AO", new_post_path, id: "new_post", class: "nav-link" %>
</li>

app/views/shared/_admin_dashboard.html.erb
<%= link_to "ADMIN", admin_posts_path, class: "dropdown-item" %>

app/views/shared/_download_link.html.erb
<% if post.photo.attached? %>
  <i class="fas fa-file-download"></i>
  <%
    filename = post.photo.blob.filename.to_s
    is_zip = filename.downcase.ends_with?(".zip")
    options = is_zip ? { resource_type: "raw", format: "zip" } : {}
  %>
  <%= link_to("Télécharger le dossier", cloudinary_download_url(post.photo.key, options), class: "download-link") %>
<% else %>
  <i class="far fa-times-circle"></i><span class="no-download"> Pas de dossier à télécharger</span>
<% end %>

app/views/shared/_favorite_button.html.erb
<% if current_user.favorite_posts.exists?(id: post.id) %>
  <%= link_to favorite_post_path(post), method: :delete do %>
    <i class="fas fa-bookmark" style="color: #F9CA62"></i>
  <% end %>
<% else %>
  <%= link_to favorite_posts_path(post_id: post), method: :post do %>
    <i class="far fa-bookmark" style="color: #F9CA62"></i>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "tapas_logo.png", class: "logo_navbar" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto"> <!-- Changed mr-auto to me-auto for Bootstrap 5 -->
      <% if admin_types.include?(current_user.try(:type)) %>
        <%= render 'shared/admin_add_ao' %>
      <% end %>
      <li class="nav-item">
        <%= link_to "LISTE DES AO", posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "FAVORIS", favorites_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> <!-- Changed right to end -->
          <% if admin_types.include?(current_user.try(:type)) %>
            <%= render 'shared/admin_dashboard' %>
          <% end %>
          <%= link_to "DÉCONNEXION", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>