config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :posts
      root to: "users#index"
    end

  get '/favorites', to: 'favorite_posts#index', as: 'favorites'
  resources :favorite_posts, only: [:create, :destroy]

  resources :posts do
    resources :likes
    resources :readings
    resources :calls
    resources :teams
    resources :rejections
    resources :comments
  end
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :readings, dependent: :destroy
  has_many :calls, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_many :rejections, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  has_one_attached :photo
  has_rich_text :rich_body

  validates_presence_of :deadline, :title, :client
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, except: [:index, :show]

  def index
    @posts = Post.where('deadline >= ?', Date.today).order('deadline DESC')
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    authorize @post
    if @post.save
      PostMailer.creation_confirmation(@post).deliver_now
      redirect_to @post, notice: "L'appel d'offres vient d'être créé! "
    else
      render :new
    end
  end

  def show
    @users = User.all
    @comment = Comment.create
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: "L'appel d'offres a été modifié "
    else
      render :edit
    end
  end

  def destroy
    authorize @post
    @post.photo.purge if @post.photo.attached?
    if @post.destroy
      redirect_to posts_path, notice: "Appel d'offres supprimé "
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:deadline, :title, :description, :photo, :client, :rich_body)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_admin
    authorize :admin, :admin?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_call.html.erb
<% pre_call = @post.calls.find { |call| call.user_id == current_user.id} %>
<% if pre_call %>
  <%= link_to "J'appelle le client (#{@post.calls.count})", post_call_path(@post, pre_call), method: :delete, class: "ranking-link" %>
<% else %>
  <%= link_to "J'appelle le client", post_calls_path(@post), method: :post, class: "ranking-link" %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.text_field :client, class: "form-control", placeholder: "Ajouter le nom du client" %>
  </div>
  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Ajouter le titre de la mission" %>
  </div>
  <div class="form-inputs">
    <%= f.rich_text_area :rich_body, placeholder: "Ajouter si nécessaire une description" %>
  </div>
  <div class="form-group form_date">
    <%= f.label :"Date limite de réponse :" , class: "control-label"%>
    <%= f.date_field :deadline %>
  </div>
  <div class="form-group form_files">
    <% if @post.photo.attached? %>
    <p>Un dossier est déjà joint à l'appel d'offre, vous pouvez le remplacer ci-dessous.</p>
    <% end %>
    <%= f.label :"Dossier à joindre (uniquement au format zip ou pdf) :", class: "control-label" %>
    <%= f.file_field :photo, direct_upload: true %>
  </div>
  <%= f.submit 'Enregistrer', class: "btn btn-outline-success" %>
  <%= link_to 'Annuler', posts_path, class: "btn btn-outline-danger" %>
<% end %>

app/views/posts/_like.html.erb
<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <span><%= link_to "Je réponds (#{@post.likes.count})", post_like_path(@post, pre_like), method: :delete, class: "ranking-link" %></span>
<% else %>
  <%= link_to 'Je réponds', post_likes_path(@post), method: :post, class: "ranking-link" %>
<% end %>

app/views/posts/_post.html.erb
<div class="card-ao">
  <div class="container-card">
    <p class="card-date"><%= post.deadline.strftime("%d/%m/%Y") %></p>
    <div class="logos_new_favorite">
      <% if (Time.now - post.created_at <= 7.days) %>
        <i class="far fa-bell project-new animate__animated animate__swing animate__slow animate__repeat-2"></i>
      <% end %>
      <div class="card-favorite">
        <% unless current_user.favorite_posts.exists?(id: post.id) %>
          <%= link_to favorite_posts_path(post_id: post), method: :post do %>
            <i class="far fa-bookmark" style="color: #F9CA62"></i>
          <% end %>
        <% else %>
          <%= link_to favorite_post_path(post), method: :delete do %>
            <i class="fas fa-bookmark" style="color: #F9CA62"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <h2 class="card-client"><%= post.client.to_s.truncate(50).upcase rescue "Client" %></h2>
    <h2 class="card-title"><%= post.title.to_s.truncate(75).capitalize rescue "Titre" %></h2>

    <!-- Description tronquée ou message par défaut -->
    <% if post.rich_body.present? %>
      <p class="card-description"><%= strip_tags(post.rich_body.to_s).truncate(150) %></p>
    <% else %>
      <p class="card-description text-muted"><em>Aucune description disponible</em></p>
    <% end %>

    <% if post.photo.attached? %>
      <div class="attachment-indicator">
        <%= link_to rails_blob_path(post.photo, disposition: :attachment), title: "Télécharger la pièce jointe", class: "download-attachment-link" do %>
          <i class="fas fa-paperclip project-attachment" title="Télécharger la pièce jointe"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="container-link">
    <%= link_to "Voir l'annonce", post_path(post), class: "card-link" %>
  </div>
</div>

app/views/posts/_reading.html.erb
<% pre_reading = @post.readings.find { |read| read.user_id == current_user.id} %>
<% if pre_reading %>
  <%= link_to "Je lis l'ao (#{@post.readings.count})", post_reading_path(@post, pre_reading), method: :delete, class: "ranking-link" %>
<% else %>
  <%= link_to "Je lis l'ao", post_readings_path(@post), method: :post, class: "ranking-link" %>
<% end %>

app/views/posts/_rejection.html.erb
<% pre_rejection = @post.rejections.find { |rejection| rejection.user_id == current_user.id} %>
<% if pre_rejection %>
  <%= link_to "Pas pour moi (#{@post.rejections.count})", post_rejection_path(@post, pre_rejection), method: :delete, class: "ranking-link" %>
<% else %>
  <%= link_to "Pas pour moi", post_rejections_path(@post), method: :post, class: "ranking-link" %>
<% end %>

app/views/posts/_table_position.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col"><i class="fas fa-book-reader"></i><%= render 'reading' %></th>
      <th scope="col"><i class="fas fa-phone"></i><%= render 'call' %></th>
      <th scope="col"><i class="fas fa-pencil-alt"></i><%= render 'like' %></th>
      <th scope="col"><i class="fas fa-user-plus"></i><%= render 'team' %></th>
      <th scope="col"><i class="fas fa-times-circle"></i><%= render 'rejection' %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% if @post.readings.empty?  %>
        <td>#</td>
      <% else %>
        <td>
          <% @post.readings.each do |reading| %>
            <p><%= reading.user.first_name %></p>
          <% end %>
        </td>
      <% end %>
      <% if @post.calls.empty?  %>
        <td>#</td>
      <% else %>
        <td>
          <% @post.calls.each do |call| %>
            <p><%= call.user.first_name %></p>
          <% end %>
        </td>
      <% end %>
      <% if @post.likes.empty?  %>
        <td>#</td>
      <% else %>
        <td>
          <% @post.likes.each do |like| %>
            <p><%= like.user.first_name %></p>
          <% end %>
        </td>
      <% end %>
      <% if @post.teams.empty?  %>
        <td>#</td>
      <% else %>
        <td>
          <% @post.teams.each do |team| %>
            <p><%= team.user.first_name %></p>
          <% end %>
        </td>
      <% end %>
      <% if @post.rejections.empty?  %>
        <td>#</td>
      <% else %>
        <td>
          <% @post.rejections.each do |rejection| %>
            <p><%= rejection.user.first_name %></p>
          <% end %>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/posts/_team.html.erb
<% pre_team = @post.teams.find { |team| team.user_id == current_user.id} %>
<% if pre_team %>
  <%= link_to "J'intègre l'équipe (#{@post.teams.count})", post_team_path(@post, pre_team), method: :delete, class: "ranking-link" %>
<% else %>
  <%= link_to "J'intègre l'équipe", post_teams_path(@post), method: :post, class: "ranking-link" %>
<% end %>

app/views/posts/edit.html.erb
<div class="container edit_post">
  <h1>Modifier <span>l'appel d'offres</span></h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="wrapper">
  <% if @posts.blank? %>
    <div class="container list-posts">
      <h1>Liste des <span>appels d'offres</span></h1>
      <%= image_tag ("empty.svg"), class:"empty-img"%>
    </div>
  <% else %>
    <div class="container list-posts">
      <h1>Liste des <span>appels d'offres</span></h1>
        <div class="cards">
          <%= render @posts %>
        </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container new_post">
  <h1>Créer un nouvel <span>appel d'offres</span></h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="show_intro">
      <div class="show_description">
        <span class="show_favorite">
          <% unless current_user.favorite_posts.exists?(id: @post.id) %>
            <%= link_to favorite_posts_path(post_id: @post), method: :post do %>
              <i class="far fa-bookmark" style="color: #F9CA62"></i>
            <% end %>
          <% else %>
            <%= link_to favorite_post_path(@post), method: :delete do %>
              <i class="fas fa-bookmark" style="color: #F9CA62"></i>
            <% end %>
          <% end %>
        </span>
        <h2 class="show_title"><%= @post.client.upcase %></h2>
        <h2><%= @post.title.capitalize %></h2>
      </div>
      <div class="show_date">
        <p>Date limite de réponse : <%= @post.deadline.strftime("%d/%m/%Y") %></p>
      </div>
    </div>

    <div class="show_text">
      <% if @post.rich_body.present? %>
        <p><%= @post.rich_body %></p>
      <% else %>
        <p>Pas de description.</p>
      <% end %>
    </div>

    <div class="show_link">
      <%= render partial: "shared/download_link", locals: { post: @post } %>
    </div>

    <div class="show_text">
      <h3>Positionnement</h3>
      <%= render 'table_position' %>
    </div>

    <div class="show_comment">
      <div class="card-body">
        <h3>Commentaires</h3>
        <p>
          <% if @post.comments.present? %>
            <% @post.comments.each do |c| %>
              <% if c.user.present? %>
                <div>
                  <small>
                    <strong><%= c.user.first_name %></strong> (il y a <%= time_ago_in_words(c.created_at) %>)
                  </small>
                  <p class="mt-1 ml-4">
                    <%= c.body %>
                  </p>
                </div>
              <% end %>
            <% end %>
          <% else %>
            Il n'y a pas encore de commentaires pour cet ao.
          <% end %>
        </p>

        <%= form_for [@post, @comment] do |f| %>
          <div class="form-group">
            Vous voulez laisser un commentaire ?
            <%= f.text_area :body, class: "form-control", placeholder: "Écrivez votre commentaire ici.", rows: 3 %>
            <%= f.hidden_field :user_id, value: current_user.id %>
          </div>
          <%= f.submit "Enregistrer votre commentaire", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div>
      <%= link_to "MODIFIER", edit_post_path(@post), class: "btn btn-outline-primary" if policy(Post).update? %>
      <%= link_to "SUPPRIMER", post_path(@post), method: :delete, data: { confirm: "Vous êtes sûr ?" }, class: "btn btn-outline-danger" if policy(Post).destroy? %>
    </div>
  </div>
</div>